name: 'moneybook deploy'
on:
  pull_request:
    types:
      - closed
    branches: [main]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote connect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            fuser -k 3000/tcp
            cd web-moneybook-1
            git pull
            npm install
            npm run build
            npm run start
